apiVersion: v2
name: pagopa-fdr-3-chart
description: Flussi di rendicontazioni
type: application
version: "1.176.0"
appVersion: "1.1.65-2-PIDM-1276-internal-ops"
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: core
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: scheduler
