apiVersion: v2
name: pagopa-fdr-chart
description: Flussi di rendicontazioni
type: application
version: "1.7.0"
appVersion: "1.0.4"
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
