apiVersion: v2
name: pagopa-fdr-3-chart
description: Flussi di rendicontazioni
type: application
version: "1.171.0"
appVersion: "1.1.63-1-fix/PIDM-1215"
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: core
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: scheduler
