apiVersion: v2
name: pagopa-fdr-3-chart
description: Flussi di rendicontazioni
type: application
version: "1.183.0"
appVersion: "1.2.0-1-PAGOPA-3480-app"
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: core
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: scheduler
